const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let state={media:[],availability:[],requests:[]};
const labels={overview:'Visão geral',media:'Fotos e vídeos',calendar:'Agenda',requests:'Solicitações',security:'Segurança'},statusLabel={available:'Disponível',pending:'Em negociação',booked:'Reservada',blocked:'Bloqueada'},requestLabel={new:'Novo',contacted:'Em contato',approved:'Aprovado',declined:'Recusado'};
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}
async function api(url,options={}){const r=await fetch(url,options),body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Não foi possível concluir.');return body}
function go(id){$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));$$('aside nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));$('#page-title').textContent=labels[id];$('#quick-upload').hidden=id!=='media';$('aside').classList.remove('open')}
$$('[data-panel]').forEach(b=>b.onclick=()=>go(b.dataset.panel));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#menu').onclick=()=>$('aside').classList.toggle('open');
function formatDate(date){return new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`))}
function render(){
  $('#media-count').textContent=state.media.length;$('#booking-count').textContent=state.availability.filter(x=>x.status==='booked'&&x.date>=new Date().toISOString().slice(0,10)).length;const news=state.requests.filter(x=>x.status==='new').length;$('#new-count').textContent=news;$('#request-badge').textContent=news;
  $('#upcoming').innerHTML=state.availability.filter(x=>x.date>=new Date().toISOString().slice(0,10)).slice(0,5).map(x=>`<div class="date-row"><strong>${formatDate(x.date)}</strong><span class="status ${x.status}">${statusLabel[x.status]}</span><span>${esc(x.note)||'Sem observação'}</span></div>`).join('')||'<p>Nenhuma data cadastrada.</p>';
  $('#media-grid').innerHTML=state.media.map(x=>`<article class="media-card">${x.type==='video'?`<video src="${x.url}" controls preload="metadata"></video>`:`<img src="${x.url}" alt="${esc(x.alt)}" loading="lazy">`}<div><span><strong>${esc(x.title)}</strong>${x.type==='video'?'Vídeo':'Foto'}</span><button data-delete-media="${x.id}">Excluir</button></div></article>`).join('')||'<p>Nenhuma mídia publicada.</p>';
  $('#calendar-list').innerHTML=state.availability.map(x=>`<div class="date-row"><strong>${formatDate(x.date)}</strong><span class="status ${x.status}">${statusLabel[x.status]}</span><span>${esc(x.note)||'Sem observação'}</span><button class="danger" data-delete-date="${x.date}">Remover</button></div>`).join('')||'<p>Nenhuma data definida. Datas sem marcação aparecem como disponíveis para consulta.</p>';
  $('#requests-list').innerHTML=state.requests.map(x=>`<div class="request-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.phone)}${x.email?` • ${esc(x.email)}`:''}</small></div><div><strong>${formatDate(x.date)}</strong><small>${esc(x.event_type)} • ${x.guests||'?'} pessoas</small></div><span>${esc(x.message)||'Sem mensagem'}</span><select data-request="${x.id}">${Object.entries(requestLabel).map(([v,l])=>`<option value="${v}" ${x.status===v?'selected':''}>${l}</option>`).join('')}</select></div>`).join('')||'<p>Nenhuma solicitação recebida.</p>';
}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){try{state=await api('/api/admin/dashboard');$('#login').classList.add('hidden');render()}catch{$('#login').classList.remove('hidden')}}
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-error').textContent='';try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});e.currentTarget.reset();await load()}catch(err){$('#login-error').textContent=err.message}};
$('#logout').onclick=async()=>{await api('/api/admin/logout',{method:'POST'});location.reload()};
const mediaDialog=$('#media-dialog'),dateDialog=$('#date-dialog');$('#add-media').onclick=$('#quick-upload').onclick=()=>mediaDialog.showModal();$('#add-date').onclick=()=>dateDialog.showModal();$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#media-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(!fd.get('featured'))fd.set('featured','0');try{await api('/api/admin/media',{method:'POST',body:fd});mediaDialog.close();e.currentTarget.reset();toast('Mídia publicada no site');await load()}catch(err){toast(err.message)}};
$('#date-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{await api(`/api/admin/availability/${f.date}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:f.status,note:f.note})});dateDialog.close();e.currentTarget.reset();toast('Agenda atualizada');await load()}catch(err){toast(err.message)}};
$('#media-grid').onclick=async e=>{const id=e.target.dataset.deleteMedia;if(!id||!confirm('Excluir esta mídia do site?'))return;try{await api(`/api/admin/media/${id}`,{method:'DELETE'});toast('Mídia excluída');await load()}catch(err){toast(err.message)}};
$('#calendar-list').onclick=async e=>{const date=e.target.dataset.deleteDate;if(!date||!confirm('Remover esta marcação da agenda?'))return;await api(`/api/admin/availability/${date}`,{method:'DELETE'});toast('Data removida');await load()};
$('#requests-list').onchange=async e=>{const id=e.target.dataset.request;if(!id)return;try{await api(`/api/admin/requests/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:e.target.value})});toast('Solicitação atualizada');await load()}catch(err){toast(err.message)}};
$('#password-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(f.password!==f.confirm)return toast('As senhas não coincidem.');try{await api('/api/admin/password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:f.password})});e.currentTarget.reset();toast('Senha alterada com sucesso')}catch(err){toast(err.message)}};load();
